language: go
go:
  - 1.4
sudo: false
install:
  - go get github.com/spf13/hugo
  - gem install bundler
  - bundle install --without development --deployment --jobs=3 --retry=3 --binstubs
cache:
  directories:
  - vendor/bundle
before_script:
 - chmod +x _bin/deploy.sh
script:
 - bin/compass compile -e production --force
 - hugo
 - bundle exec htmlproof public --disable-external
after_script:
  - _bin/deploy.sh
branches:
  only:
  - master
env:
  global:
    - RESET=false
    - GH_REF=github.com/pickleshb/cjb_science.git
    - secure: "TdX45aO8w/c/A9a0KQ3mrCoBMtDLYrLE7rUOa/WEZWIG6DvWLw7baNG8lhZT+8icNoDbDBLl8hguq+VMiMH4qiQByHWaIdeH/irFXcSOu4exANmEJy/KawDXg3vh4P3y6As+ydcIyrrrs9gS062kTmwzhJuvnu/mW3vpBgqCRMmDdjAM+b5qCUeXg4Mejz6mnccQQ5xNClHlP72WFgHBn36cC7u/b4UuY3/8pCvvXWH2b18lgSrxniVPYhvB9gtAo68KVNBXm6lwXzw6e7ukIj5YwrtDHLR0pDIFAg5vlMlLA5nBaZlyJtKBrgNhomFOV1h8qQ6VlsckgRFIb4hxWsc6b69i/8+r+2HbL8PTMFN7yAyhDJbnYSJ/GW4ZsHZPyVsd+9b4ZbGgv68y2AQrTVLzGc/WnlrhUxoVowYHzrUBUYxzkH7C85Jql12pEF+cWpjqcxeoEJNxUeH/ayQdnVoY+KBR79K1/agUy1/13U5BwCDABJMT857vFWB+JCJ4yndmIkvmkOzwpxAUWl5tU99eXcnSD6lsTExhgFcSm9RKLqlSLa5OZiJUXPgQSZzq3a1SgPX0W9YO0BioIRFudiSdEtDp3GFw/ThTeZUBMVHcjl2Hv19QuSU4KI6O90wjWvYhU552xuxIf0eOKfZoDr65oZRoxozFc8FpwEMEF60="
