language: go
go:
  - 1.4
sudo: false
install:
  - go get github.com/spf13/hugo
  - gem install bundler
  - bundle install --without development --deployment --jobs=3 --retry=3 --binstubs
cache:
  directories:
  - vendor/bundle
before_script:
 - chmod +x _bin/deploy.sh
script:
 - bin/compass compile -e production --force
 - hugo
 - bundle exec htmlproof public
after_script:
  - _bin/deploy.sh
branches:
  only:
  - master
env:
  global:
    - RESET=false
    - GH_REF=github.com/pickleshb/cjb_science.git
    - secure: "V/weTHvMI9rmEXnGsy52OzlvOmzT4WrvLpJbaS4UMWzuTLXvCdqiXZWepfceJ6S9AQN0M56CSBVkQ60lCVrnuUh8F6Uz9vG9ifvNgeYae5WDvHd1tiJ4nIAtrWW9ySbwlpymxekWKcLGpLM6wNNx8cbtFPJ4YD1U/8kWwrkqV6rhQyZXXJZ+20GE0XXdlXw628Nkr0kGn18dklBltjTsMdRk8YNV60dGZEaPP3Lsm4F7IXSNiP6CPrstuLD7aAILSISy9WjRvtE41NYPMmPIh/63fO24EnRdtWaRLKAuPgBwDZo8464uz/pV9HdNFyk6YDWVlQxjBMb3/NpvbxewPsVxBI/jEiBTGy+NR7pwxlQ509XmXuKTKzSoXDsnxeElZJ9gd5Rt94d/BCCQEQSEiGkmjpGHUkPskIax/YgCuGEunelHUgLIykGyt/ZVy5TO/SynUqBBJ70EXW8fkoJy53/57iRHEV61/N3KNp/wy5YHR/X9QYPH1tdYZ7MDBqUzQer6srd0Ubbb9/VyGfRR5OwcpYLcdPfIky+Ti/Kurm20EK/RFyevKXwt/jcGwB9Qo4q60ysYOYz9wk7V5u4b86dVpklcRY7aW7pXJi0mBg8rqSRmI8zGcuSlyQHtVyl63XDK0uzmrMmKKdLaJkknCTSYsdUJT8EhvWWGTWDarYs="
