baseurl = "http://science.harrybridge.co.uk/"
languageCode = "en-gb"
title = "Chris Bridge Science"
PluralizeListTitles=false
canonifyurls = false

# [taxonomies]
# photo = "photo"
# title = "title"

[[menu.main]]
    name = "Years"
    weight = 0
    identifier = "Years"
    url = "/year/"
